const app=document.querySelector('#app'), modal=document.querySelector('#finish');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Date(d).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const equipment=(rows,ready=[])=>rows.map(([name,qty,note],i)=>({name,qty,note,ready:ready.includes(i)}));
function seed(){const now=Date.now();return {read:false,events:[
{id:1,beo:'021045',name:'Leadership lunch',type:'Lunch buffet',room:'Wilson Room',floor:'2nd floor',guests:100,start:now+95*60000,team:['Alex','Blair'],changed:true,items:equipment([['Chafers',6,'5 hot dishes + 1 extra station · Revised'],['Dinner plates',100,'1 per guest'],['Serving utensils',6,'1 per buffet station'],['Water pitchers',10,'1 per 10 guests'],['Tray stands',4,'Fixed quantity'],['Bus tubs',3,'Fixed quantity']],[1,3,4])},
{id:2,beo:'021053',name:'Afternoon coffee break',type:'Coffee break',room:'Wilson Room',floor:'2nd floor',guests:80,start:now+195*60000,team:['Alex'],items:equipment([['Coffee urns',2,'1 per 40 guests'],['Coffee cups',80,'1 per guest'],['Saucers',80,'1 per guest'],['Service trays',4,'Fixed quantity']])},
{id:3,beo:'021067',name:'Foundation dinner',type:'Dinner buffet',room:'Grand Ballroom',floor:'4th floor',guests:240,start:now+315*60000,team:['Alex','Jamie','Blair'],items:equipment([['Chafers',8,'8 hot buffet dishes'],['Dinner plates',240,'1 per guest'],['Serving utensils',8,'1 per buffet station'],['Water pitchers',24,'1 per 10 guests'],['Bus tubs',6,'Fixed quantity']])},
{id:4,beo:'021038',name:'Board breakfast',type:'Breakfast buffet',room:'Monroe Room',floor:'2nd floor',guests:40,start:now-30*60000,team:['Alex'],completed:{name:'Alex Lee',at:now-95*60000,photo:null},items:equipment([['Chafers',3,'3 hot buffet dishes'],['Breakfast plates',40,'1 per guest'],['Serving utensils',3,'1 per hot dish']],[0,1,2])}]};}
let state;try{state=JSON.parse(localStorage.getItem('steward-prototype-v1'))||seed();}catch{state=seed();}
let tab='events',filter='all',selected=null,photo=null;
function save(){try{localStorage.setItem('steward-prototype-v1',JSON.stringify(state));}catch{toast('Preview saved for this session only.');}}
const ready=e=>e.items.filter(i=>i.ready).length;
const deadline=e=>e.start-60*60000;
function countdown(e){if(e.completed)return 'Setup complete';const secs=Math.floor((deadline(e)-Date.now())/1000),abs=Math.abs(secs),h=Math.floor(abs/3600),m=Math.floor(abs%3600/60),s=abs%60;return `${secs<0?'Overdue by ':''}${h?`${h}h `:''}${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s${secs>=0?' to setup':''}`;}
function toast(s){const el=document.querySelector('#toast');el.textContent=s;el.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.style.display='none',3500);}
function card(e){const count=ready(e);return `<button class="card" data-event="${e.id}"><div class="card-top"><span class="time">${fmt(e.start)} <span style="color:#8c978c;font-weight:400">· ${esc(e.type)}</span></span><span class="status ${e.completed?'complete':e.changed&&!state.read?'urgent':''}">${e.completed?'✓ Complete':e.changed&&!state.read?'Updated':count?'In progress':'To do'}</span></div><h3>${esc(e.name)}</h3><div class="room"><span>⌖ ${esc(e.room)}</span><span>${e.guests} guests</span></div><div class="progress"><div style="width:${count/e.items.length*100}%"></div></div><div class="card-bottom"><span>${count} of ${e.items.length} items ready</span><span class="${e.completed?'':'countdown'}" data-clock="${e.id}">${countdown(e)}</span></div></button>`;}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelector('#badge').hidden=state.read;const today=new Date().toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'});if(selected){detail();return;}if(tab==='events'){const total=state.events.length,done=state.events.filter(e=>e.completed).length;app.innerHTML=`<div class="eyebrow">${today}</div><h1>Let’s get set, Alex.</h1><p class="subtitle">Your events, your checklist. One smooth shift.</p><div class="stats"><div><strong>${total}</strong><span>Assigned events</span></div><div><strong>${total-done}</strong><span>Still to set</span></div><div><strong>${done}</strong><span>Complete</span></div></div>${!state.read?'<div class="alert"><span>↻</span><div><strong>A little change to your lunch setup</strong>Leadership lunch now needs 6 chafers. Maria added an extra station.<br><button data-open-change>Review change →</button></div></div>':''}<div class="section-title"><h2>Your lineup</h2><span>In event time order</span></div><div class="filters">${[['all','All events'],['todo','Outstanding'],['done','Complete']].map(([v,t])=>`<button class="filter ${filter===v?'active':''}" data-filter="${v}">${t}</button>`).join('')}</div><div class="cards">${state.events.filter(e=>filter==='all'||(filter==='done'?e.completed:!e.completed)).sort((a,b)=>a.start-b.start).map(card).join('')||'<div class="empty">Nothing here. You’re all caught up.</div>'}</div>`;}else if(tab==='updates'){app.innerHTML=`<div class="eyebrow">Stay in the loop</div><h1>Shift updates.</h1><p class="subtitle">Changes from your supervisor, all in one place.</p><button class="card" data-open-change><div class="card-top"><span class="eyebrow">Equipment revised</span><span class="status urgent">${state.read?'Reviewed':'New'}</span></div><h3>One extra buffet station</h3><p class="note">Maria Santos changed chafers from 5 → 6 for Leadership lunch, BEO 021045. Everything else stays the same.</p><div class="room">⌖ Wilson Room · ${fmt(state.events[0].start)}</div><p class="note">Review event →</p></button>`;}else{app.innerHTML=`<div class="eyebrow">Your profile</div><h1>Alex’s shift.</h1><p class="subtitle">Banquet steward · Today’s operation</p><div class="card shift-list"><div class="row"><span>Supervisor</span><strong>Maria Santos</strong></div><div class="row"><span>Primary location</span><strong>2nd floor</strong></div><div class="row"><span>Working with</span><strong>Blair & Jamie</strong></div><div class="row"><span>Events complete</span><strong>${state.events.filter(e=>e.completed).length} / 4</strong></div></div><p class="note">This is a team prototype with fictional BEOs. Your changes stay in this browser. Reset any time to run another demonstration.</p><button class="reset" id="reset">Reset sample events</button>`;}bind();}
function detail(){const e=state.events.find(x=>x.id===selected),count=ready(e);app.innerHTML=`<button class="back" id="back">← Back to my events</button><div class="eyebrow">BEO #${e.beo} · ${esc(e.type)}</div><h1>${esc(e.name)}</h1><div class="detail-head"><div class="row" style="margin:0"><span>${esc(e.room)} · ${esc(e.floor)}</span><span>${e.guests} guests</span></div><h2>${fmt(e.start)} event start</h2><div class="room">${e.team.map(p=>`<span class="person"><b>${esc(p[0])}</b>${esc(p)}</span>`).join('')}</div><div class="row"><span>Setup due ${fmt(deadline(e))}</span><strong class="deadline" data-clock="${e.id}">${countdown(e)}</strong></div></div>${e.changed&&!state.read?'<div class="alert"><span>↻</span><div><strong>Equipment changed by Maria</strong>Chafers increased from 5 to 6 for an extra station.<br><button id="ack">Got it, acknowledge change</button></div></div>':''}<div class="section-title"><h2>Equipment checklist</h2><span>${count} / ${e.items.length} ready</span></div><p class="note">Check an item when its full quantity is ready. You share this setup with ${e.team.length>1?esc(e.team.filter(x=>x!=='Alex').join(' and ')):'your supervisor'}.</p><div>${e.items.map((i,n)=>`<div class="equipment ${i.ready?'ready':''}"><button class="check ${i.ready?'checked':''}" data-item="${n}" aria-label="${i.ready?'Uncheck':'Check'} ${esc(i.name)}" aria-pressed="${i.ready}" ${e.completed?'disabled':''}>${i.ready?'✓':''}</button><div><strong>${esc(i.name)}</strong><p>${esc(i.note)}</p></div><span class="qty">${i.ready?i.qty:0} / ${i.qty}</span></div>`).join('')}</div>${e.completed?`<div class="audit"><strong>✓ Setup complete</strong><br>Completed by ${esc(e.completed.name)} · ${new Date(e.completed.at).toLocaleString()}<br>BEO #${e.beo} · ${e.completed.photo?'Setup photo attached':'Sample completion record'}${e.completed.photo?`<img src="${esc(e.completed.photo)}" alt="Completed event setup">`:''}</div>`:`<button class="primary" id="finish-button" ${count<e.items.length?'disabled':''}>${count===e.items.length?'Complete setup & add photo →':`${e.items.length-count} items left to prepare`}</button><p class="fine">A photo and your completion time will be recorded.</p>`}`;bind();}
function bind(){app.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.event);render();window.scrollTo(0,0);});app.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});app.querySelectorAll('[data-open-change]').forEach(b=>b.onclick=()=>{selected=1;tab='events';render();window.scrollTo(0,0);});app.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{const e=state.events.find(x=>x.id===selected),item=e.items[Number(b.dataset.item)];item.ready=!item.ready;save();render();if(ready(e)===e.items.length)openFinish();});const back=document.querySelector('#back');if(back)back.onclick=()=>{selected=null;tab='events';render();};const ack=document.querySelector('#ack');if(ack)ack.onclick=()=>{state.read=true;save();render();toast('Change acknowledged. Your checklist is up to date.');};const finish=document.querySelector('#finish-button');if(finish)finish.onclick=openFinish;const reset=document.querySelector('#reset');if(reset)reset.onclick=()=>{state=seed();save();tab='events';filter='all';render();toast('Sample events reset. Ready for a new demo.');};}
function openFinish(){photo=null;document.querySelector('#photo').value='';document.querySelector('#photo-preview').hidden=true;document.querySelector('#confirm').disabled=true;modal.showModal();}
document.querySelector('#photo').onchange=async event=>{const file=event.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return toast('Choose an image for your setup photo.');try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();photo=canvas.toDataURL('image/jpeg',.75);const preview=document.querySelector('#photo-preview');preview.src=photo;preview.hidden=false;document.querySelector('#confirm').disabled=false;}catch{toast('Could not read this photo. Please choose another.');}};
document.querySelector('#confirm').onclick=()=>{if(!photo)return;const e=state.events.find(x=>x.id===selected);e.completed={name:'Alex Lee',at:Date.now(),photo};save();modal.close();render();toast('Setup complete. Nice work, Alex!');};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;selected=null;render();window.scrollTo(0,0);});document.querySelector('.brand').onclick=event=>{event.preventDefault();tab='events';selected=null;render();};document.querySelector('#profile').onclick=()=>{tab='shift';selected=null;render();};setInterval(()=>document.querySelectorAll('[data-clock]').forEach(el=>{const e=state.events.find(x=>x.id===Number(el.dataset.clock));el.textContent=countdown(e);}),1000);render();
